---
name: Test, Lint & Deploy
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: 'Install Node'
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'
            - name: 'Install Deps'
              run: npm install
            - name: 'Test'
              run: npx vitest